name: CI Tests
on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  push:
  pull_request:
  schedule:
    # minute hour day month day-of-week
    # Run at 12:25 UTC every day
    - cron: '25 12 * * *'

jobs:
  build-and-test:
    uses: bemanproject/infra-workflows/.github/workflows/reusable-beman-build-and-test.yml@1.0.0
    with:
      matrix_config: >
        {
          "gcc": [
            { "versions": ["14"],
              "tests": [
                { "cxxversions": ["c++26"],
                  "tests": [
                    { "stdlibs": ["libstdc++"],
                      "tests": [
                        "Debug.Default", "Release.Default", "Release.ASan",
                        "Debug.Coverage"
                      ]
                    }
                  ]
                }
              ]
            },
            { "versions": ["13", "12"],
              "tests": [
                { "cxxversions": ["c++26"],
                  "tests": [
                    { "stdlibs": ["libstdc++"],
                      "tests": [
                        "Debug.Default", "Release.Default", "Release.ASan"
                      ]
                    }
                  ]
                }
              ]
            }
          ],
          "clang": [
            { "versions": ["21", "20", "18", "17"],
              "tests": [
                { "cxxversions": ["c++26"],
                  "tests": [
                    { "stdlibs": ["libstdc++", "libc++"],
                      "tests": [
                        "Debug.Default", "Release.Default", "Release.ASan"
                      ]
                    }
                  ]
                }
              ]
            },
            { "versions": ["19"],
              "tests": [
                { "cxxversions": ["c++26"],
                  "tests": [
                    { "stdlibs": ["libstdc++", "libc++"],
                      "tests": [
                        "Debug.Default", "Release.Default", "Release.ASan"
                      ]
                    }
                  ]
                }
              ]
            }
          ]
        }

  create-issue-when-fault:
    runs-on: ubuntu-latest
    needs: [build-and-test]
    if: failure() && github.event_name == 'schedule'
    steps:
      # See https://github.com/cli/cli/issues/5075
      - uses: actions/checkout@v4
      - name: Create issue
        run: |
          issue_num=$(gh issue list -s open -S "[SCHEDULED-BUILD] Build & Test failure" -L 1 --json number | jq 'if length == 0 then -1 else .[0].number end')

          body="**Build-and-Test Failure Report**
          - **Time of Failure**: $(date -u '+%B %d, %Y, %H:%M %Z')
          - **Commit**: [${{ github.sha }}](${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }})
          - **Action Run**: [View logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }})

          The scheduled build-and-test triggered by cron has failed.
          Please investigate the logs and recent changes associated with this commit or rerun the workflow if you believe this is an error."

          if [[ $issue_num -eq -1 ]]; then
            gh issue create --repo ${{ github.repository }} --title "[SCHEDULED-BUILD] Build & Test failure" --body "$body"
          else
            gh issue comment --repo ${{ github.repository }} $issue_num --body "$body"
          fi
        env:
          GH_TOKEN: ${{ github.token }}
